### ISSUE TITLE
Guides section link on README goes nowhere

### ISSUE THREAD

**Issue by Robinlovelace** [darribas/gds_env#44]
I tried to see the guide for running in Docker and clicked on a link to here: https://github.com/darribas/gds_env/blob/master/guides

**Comment by darribas** [comment]
Thanks for reporting! Yes, that's because the files are designed to work on the deployed website:

https://darribas.org/gds_env/guides/

To keep it simple and maintainable, the files are structured in the repo in a way that makes them "work" on the website, but not necessarily on the repo. So, I should probably make that explicit somewhere on the repo that all documentation is thought to be accessed through the website https://darribas.org/gds_env/

Closing for now but feel free to open up again if want to follow the discussion on this.

**Comment by Robinlovelace** [comment]
Great to see that, but isn't the https://github.com/darribas/gds_env/blob/master/guides link hardcoded in the `README.md` file?

**Comment by Robinlovelace** [comment]
OK, see that the answer is NO

```
[Guides section](guides)
```

Good enough for me, may confuse others who visit this readme though.
